"""Baseline generator-torque and blade-pitch control for published MOST."""

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.io import loadmat


@dataclass(frozen=True)
class MostBaselineController:
    """Published IEA 15 MW baseline controller with explicit control settings.

    The source block filters rotor speed, looks up generator torque, and uses
    a pitch PI regulator with sensitivity scheduled by the preceding pitch.
    ``simulate`` samples the continuous block at the supplied output times.
    """

    omega_gen: np.ndarray
    generator_torque: np.ndarray
    omega_max: float
    torque_max_rate: float
    pitch_max_rate: float
    kp: float
    ki: float
    sensitivity: tuple[float, float, float]
    initial_omega: float
    initial_pitch: float

    @classmethod
    def iea15mw(cls) -> "MostBaselineController":
        """Published MOST IEA 15 MW settings generated by pinned MATLAB.

        The values come from ``Steady_States_IEA15MW.m`` and
        ``Controller_IEA15MW.m`` in the pinned Applications repository.
        """
        return cls(
            omega_gen=np.array([
                0, 0.22600399063360546, 0.22601399063360547,
                0.26368298907253973, 0.30135198751147396,
                0.33902098595040819, 0.37668998438934242,
                0.41435898282827671, 0.45202798126721094,
                0.48969697970614517, 0.52736597814507946,
                0.56503497658401369, 0.60270397502294792,
                0.64037297346188216, 0.67804197190081639,
                0.71571097033975062, 0.75337996877868485,
                0.79168142548558273, 0.79168142548558285,
                1.187522138228374,
            ]),
            generator_torque=np.array([
                0, 0, 1599404.2758444315, 2176966.9310104754,
                2843385.3792789886, 3598659.6206499701,
                4442789.6551234201, 5375775.4826993374,
                6397617.1033777259, 7508314.5171585791,
                8707867.7240419015, 9996276.7240276933,
                11373541.517115954, 12839662.103306683,
                14394638.482599881, 16038470.654995548,
                17771158.62049368, 19624044.358588327,
                19624044.358588323, 19624044.016000021,
            ]),
            omega_max=0.79168142548558273,
            torque_max_rate=4500000,
            pitch_max_rate=0.12217304763960307,
            kp=-25098466.833301917,
            ki=-6274616.7083254801,
            sensitivity=(-319529044.25669515, -652053279.62867904,
                         -9353534.9672428276),
            initial_omega=0.57458778181839332,
            initial_pitch=0,
        )

    @classmethod
    def from_matlab_files(cls, control_file: str | Path,
                          steady_states_file: str | Path,
                          wind_speed: float) -> "MostBaselineController":
        """Use the controller tables generated for a particular MOST run."""
        control = loadmat(control_file, simplify_cells=True)["Ctrl"]["Baseline"]
        states = loadmat(steady_states_file, simplify_cells=True)[
            "SteadyStates"]["ROSCO"]["SS"]
        wind = np.asarray(states["WINDSPEED"], dtype=float)
        if (not np.isfinite(wind_speed) or wind.ndim != 1
                or not np.isfinite(wind).all()
                or not np.all(np.diff(wind) > 0)
                or not wind[0] <= wind_speed <= wind[-1]):
            raise ValueError("initial wind speed must lie within the steady-state table")
        return cls(
            omega_gen=np.asarray(control["omega_gen"], dtype=float),
            generator_torque=np.asarray(control["Cgen"], dtype=float),
            omega_max=float(control["omegaMax"]),
            torque_max_rate=float(control["torqueMaxRate"]),
            pitch_max_rate=float(control["thetaMaxRate"]),
            kp=float(control["KP"]), ki=float(control["KI"]),
            sensitivity=(float(control["c1"]), float(control["c2"]),
                         float(control["c3"])),
            initial_omega=float(np.interp(wind_speed, wind, states["ROTSPD"])),
            initial_pitch=float(np.interp(wind_speed, wind, states["BLADEPITCH"])),
        )

    def __post_init__(self):
        omega = np.asarray(self.omega_gen, dtype=float)
        torque = np.asarray(self.generator_torque, dtype=float)
        scalar = np.array([
            self.omega_max, self.torque_max_rate, self.pitch_max_rate,
            self.kp, self.ki, *self.sensitivity,
            self.initial_omega, self.initial_pitch,
        ])
        if (omega.ndim != 1 or omega.size < 2 or torque.shape != omega.shape
                or not np.isfinite(omega).all()
                or not np.isfinite(torque).all()
                or not np.all(np.diff(omega) > 0)
                or not np.isfinite(scalar).all()
                or self.torque_max_rate <= 0 or self.pitch_max_rate <= 0):
            raise ValueError("invalid MOST baseline controller settings")
        object.__setattr__(self, "omega_gen", omega)
        object.__setattr__(self, "generator_torque", torque)

    def _command(self, state, previous_pitch):
        filtered = 5*state[1]
        error = filtered-self.omega_max
        desired_torque = np.interp(filtered, self.omega_gen,
                                   self.generator_torque)
        c1, c2, c3 = self.sensitivity
        sensitivity = (c1*previous_pitch+c2)*previous_pitch+c3
        desired_pitch = np.clip(
            (self.kp*error+self.ki*state[2])/sensitivity, 0, np.pi/2,
        )
        return desired_torque, desired_pitch

    def _advance(self, state, speed_before, speed_after, step,
                 previous_torque, previous_pitch):
        def derivative(current, fraction):
            incoming = speed_before+fraction*(speed_after-speed_before)
            error = 5*current[1]-self.omega_max
            integral_rate = error if current[2] > 0 or error > 0 else 0
            return np.array([
                -5*current[0]-5*current[1]+incoming,
                current[0], integral_rate,
            ])

        k1 = derivative(state, 0)
        k2 = derivative(state+step*k1/2, .5)
        k3 = derivative(state+step*k2/2, .5)
        k4 = derivative(state+step*k3, 1)
        state = state+step*(k1+2*k2+2*k3+k4)/6
        state[2] = max(0, state[2])
        wanted_torque, wanted_pitch = self._command(state, previous_pitch)
        torque = previous_torque+np.clip(
            wanted_torque-previous_torque,
            -self.torque_max_rate*step, self.torque_max_rate*step,
        )
        pitch = previous_pitch+np.clip(
            wanted_pitch-previous_pitch,
            -self.pitch_max_rate*step, self.pitch_max_rate*step,
        )
        return state, torque, pitch

    def simulate(self, time, rotor_speed):
        """Return generator torque and pitch for a prescribed speed history.

        Inputs and outputs use seconds, rad/s, N m, and radians. The speed
        samples are linearly interpolated between output times, as in the
        source harness's From Workspace block.
        """
        time = np.asarray(time, dtype=float)
        speed = np.asarray(rotor_speed, dtype=float)
        if (time.ndim != 1 or speed.shape != time.shape or time.size < 2
                or not np.isfinite(time).all() or not np.isfinite(speed).all()
                or not np.all(np.diff(time) > 0)):
            raise ValueError("time and rotor speed must be finite aligned series")
        torque = np.empty(len(time))
        pitch = np.empty(len(time))
        # The source State-Space block has A=[-5,-5;1,0], B=[1;0], C=[0,5]
        # and initial state [0, omega0/5]. Its PI integrator starts at zero.
        state = np.array([0.0, self.initial_omega/5, 0.0])
        torque[0], _ = self._command(state, self.initial_pitch)
        pitch[0] = self.initial_pitch
        for index in range(1, len(time)):
            state, torque[index], pitch[index] = self._advance(
                state, speed[index-1], speed[index],
                time[index]-time[index-1], torque[index-1], pitch[index-1],
            )
        return torque, pitch
