"""Read the Sphere HDF5 file generated by current MATLAB BEMIO."""

import os
from pathlib import Path
import sys

import numpy as np
import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "source" / "objects"))

from bodyClass import BodyClass  # noqa: E402

SPHERE_H5 = os.environ.get("WEC_SIM_SPHERE_H5")
pytestmark = pytest.mark.skipif(not SPHERE_H5, reason="MATLAB BEMIO Sphere file not provided")


def test_matlab_generated_sphere_hydrodynamics_preprocess():
    body = BodyClass(SPHERE_H5)
    body.bodyNumber = 1
    body.readH5file()
    assert "sphere" in body.name.lower()
    assert int(np.asarray(body.dof).item()) == 6
    body.hydroStiffness = np.zeros((6, 6))
    body.viscDrag = {
        "Drag": np.zeros((6, 6)),
        "cd": np.zeros(6),
        "characteristicArea": np.zeros(6),
    }
    body.linearDamping = np.zeros((6, 6))
    body.mass = "equilibrium"
    time = np.arange(1501) * 0.01
    body.hydroForcePre(
        [], [0], len(time), time, [], 0.01, 1000, 9.81,
        "noWaveCIC", np.vstack((time, np.zeros_like(time))),
        1, [], 0, 0, 0,
    )
    for field in ("linearHydroRestCoef", "fAddedMass", "fDamping", "irkb"):
        assert np.isfinite(body.hydroForce[field]).all()
