function ellipsoid_ode45_refinement(waveType)
% Refine the pinned ode45 nonlinear-hydro force and solver sample together.
waveType = string(waveType);
assert(any(waveType == ["Regular", "RegularCIC"]), ...
    'Choose a pinned ellipsoid ode45 wave case');
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
hydroDir = fullfile(repoRoot, 'applications', 'Nonlinear_Hydro', 'hydroData');
cd(hydroDir);
if ~isfile('ellipsoid.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Nonlinear_Hydro', ...
    'ode45', waveType);
outDir = fullfile(repoRoot, 'matlab-ellipsoid-ode45-fine', waveType);
mkdir(outDir);
steps = [0.01, 0.005];
labels = {'step010', 'step005'};

for iStep = 1:numel(steps)
    step = steps(iStep);
    label = labels{iStep};
    targetDir = fullfile(fileparts(caseDir), waveType + "_" + label);
    mkdir(targetDir);
    copyfile(fullfile(caseDir, 'wecSimInputFile.m'), ...
        fullfile(targetDir, 'wecSimInputFile.m'));
    copyfile(fullfile(caseDir, 'ellipsoid.slx'), ...
        fullfile(targetDir, 'ellipsoid.slx'));
    inputFile = fullfile(targetDir, 'wecSimInputFile.m');
    contents = fileread(inputFile);
    assert(contains(contents, 'simu.dt = 0.05;') && ...
        ~contains(contents, 'simu.dtOut') && ...
        ~contains(contents, 'simu.nonlinearDt') && ...
        ~contains(contents, 'simu.cicDt'), ...
        'The pinned ellipsoid ode45 sample settings changed');
    contents = strrep(contents, 'simu.dt = 0.05;', ...
        sprintf('simu.dt = %.3f;', step));
    fid = fopen(inputFile, 'w');
    assert(fid > 0);
    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, contents);
    clear cleanup;

    cd(targetDir);
    wecSim;
    assert(strcmp(simu.solver, 'ode45') && ...
        abs(simu.dt - step) < 1e-12 && ...
        abs(simu.dtOut - step) < 1e-12 && ...
        abs(simu.nonlinearDt - step) < 1e-12 && ...
        abs(simu.cicDt - step) < 1e-12 && ...
        simu.endTime == 150 && simu.rampTime == 50 && ...
        strcmp(waves.type, lowerFirst(waveType)) && ...
        waves.height == 4 && waves.period == 6 && ...
        body(1).nonlinearHydro == 2 && pto(1).damping == 1200000, ...
        'The refined ellipsoid ode45 settings changed');
    n = round(simu.endTime / step) + 1;
    bodyRecord = output.bodies(1);
    bodyValues = [bodyRecord.time(:), bodyRecord.position, ...
        bodyRecord.velocity, bodyRecord.forceTotal, ...
        bodyRecord.forceExcitation, bodyRecord.forceRadiationDamping, ...
        bodyRecord.forceAddedMass, bodyRecord.forceRestoring, ...
        bodyRecord.forceMorisonAndViscous, bodyRecord.acceleration];
    assert(size(bodyValues, 1) == n && size(bodyValues, 2) == 55 && ...
        all(isfinite(bodyValues), 'all'), ...
        'The refined ellipsoid body output is incomplete');
    writematrix(bodyValues, fullfile(outDir, label + "_body.csv"));
    ptoRecord = output.ptos(1);
    ptoValues = [ptoRecord.time(:), ptoRecord.position, ...
        ptoRecord.velocity, ptoRecord.forceInternalMechanics, ...
        ptoRecord.powerInternalMechanics];
    assert(size(ptoValues, 1) == n && size(ptoValues, 2) == 25 && ...
        all(isfinite(ptoValues), 'all'), ...
        'The refined ellipsoid PTO output is incomplete');
    writematrix(ptoValues, fullfile(outDir, label + "_pto.csv"));
    waveValues = [output.wave.time(:), output.wave.elevation(:)];
    assert(size(waveValues, 1) == n && size(waveValues, 2) == 2 && ...
        all(isfinite(waveValues), 'all'), ...
        'The refined ellipsoid wave output is incomplete');
    writematrix(waveValues, fullfile(outDir, label + "_wave.csv"));
    close_system('ellipsoid', 0);
end
end

function value = lowerFirst(value)
value = char(value);
value(1) = lower(value(1));
end
