function oswec_passive_yaw_step_refinement(phaseSeed)
% Audit the published held-heading model's sensitivity to fixed time step.
assert(ismember(phaseSeed, [1, 3]), 'Expected published or third audit seed');
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
    'OSWEC', 'hydroData');
cd(hydroDir);
if ~isfile('oswec.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Passive_Yaw', ...
    'PassiveYawRegression');
inputFile = fullfile(caseDir, 'wecSimInputFile.m');
original = fileread(inputFile);
assert(contains(original, 'simu.dt = 0.01;') && ...
    contains(original, 'simu.endTime = 250;') && ...
    contains(original, 'waves.phaseSeed = 1;') && ...
    contains(original, 'body(1).yaw.threshold = 1;') && ...
    contains(original, 'body(2).yaw.threshold = 1;'), ...
    'Pinned passive-yaw case input changed');
outDir = fullfile(repoRoot, 'matlab-oswec-passive-yaw-refinement');
mkdir(outDir);
steps = [0.01, 0.005, 0.0025];
for dt = steps
    runOneStep(caseDir, inputFile, original, outDir, phaseSeed, dt);
end
for pair = 1:(numel(steps) - 1)
    coarse = load(fullfile(outDir, ...
        sprintf('seed-%d-dt-%g.mat', phaseSeed, steps(pair))));
    fine = load(fullfile(outDir, ...
        sprintf('seed-%d-dt-%g.mat', phaseSeed, steps(pair + 1))));
    assert(max(abs(coarse.time - fine.time(1:2:end))) < 1e-10, ...
        'Refined time grid does not align with the coarser grid');
    waveError = max(abs(coarse.wave(:, 2) - fine.wave(1:2:end, 2)));
    assert(waveError < 1e-12, ...
        'Refining the step changed incident wave elevation');
    yawDifference = max(abs(coarse.yaw - fine.yaw(1:2:end)));
    fprintf('Seed %d, steps %g / %g s: wave %.6g m; yaw %.6g rad; PTO work %.6f / %.6f J\n', ...
        phaseSeed, steps(pair), steps(pair + 1), waveError, ...
        yawDifference, coarse.work, fine.work);
end
end

function runOneStep(caseDir, inputFile, original, outDir, phaseSeed, dt)
contents = strrep(original, 'simu.dt = 0.01;', ...
    sprintf('simu.dt = %.6g;', dt));
contents = strrep(contents, 'waves.phaseSeed = 1;', ...
    sprintf('waves.phaseSeed = %d;', phaseSeed));
fid = fopen(inputFile, 'w');
assert(fid ~= -1, 'Could not write disposable passive-yaw input');
fprintf(fid, '%s', contents);
fclose(fid);
cd(caseDir);
wecSim;
assert(simu.dt == dt && simu.endTime == 250 && ...
    simu.rampTime == 100 && strcmp(simu.solver, 'ode4') && ...
    strcmp(waves.type, 'irregular') && waves.phaseSeed == phaseSeed && ...
    waves.height == 2.5 && waves.period == 8 && ...
    body(1).yaw.threshold == 1 && body(2).yaw.threshold == 1, ...
    'Refinement changed more than step or phase seed');
time = output.bodies(1).time;
yaw = output.bodies(1).position(:, 6);
yawRate = output.bodies(1).velocity(:, 6);
ptoPower = output.ptos(1).powerInternalMechanics(:, 5);
ptoForce = output.ptos(1).forceInternalMechanics(:, 5);
wave = waves.waveAmpTime;
work = -trapz(time, ptoPower);
assert(numel(time) == round(250 / dt) + 1 && ...
    isequal(size(wave), [numel(time), 2]) && ...
    all(isfinite([time, yaw, yawRate, ptoPower, ptoForce, wave]), 'all') && ...
    isfinite(work) && work > 0, ...
    'Passive-yaw refinement has missing or nonfinite output');
filename = sprintf('seed-%d-dt-%g.mat', phaseSeed, dt);
save(fullfile(outDir, filename), 'phaseSeed', 'dt', 'time', 'yaw', ...
    'yawRate', 'ptoPower', 'ptoForce', 'wave', 'work', '-v7');
end
