function oswec_nonlinear_viz_motion_refinement
% Check step-size sensitivity of the published nonlinear flap motion.
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
    'OSWEC', 'hydroData');
cd(hydroDir);
if ~isfile('oswec.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Paraview_Visualization', ...
    'OSWEC_NonLinear_Viz');
inputFile = fullfile(caseDir, 'wecSimInputFile.m');
original = fileread(inputFile);
assert(contains(original, 'simu.dt = 0.1;') && ...
    contains(original, 'simu.pressure = 1;') && ...
    contains(original, 'simu.paraview.option = 1;'), ...
    'Pinned nonlinear OSWEC input changed');
outDir = fullfile(repoRoot, 'matlab-oswec-nonlinear-viz-refinement');
mkdir(outDir);
steps = [0.1, 0.05, 0.025];
for i = 1:numel(steps)
    runOneStep(caseDir, inputFile, original, outDir, steps(i));
end
end

function runOneStep(caseDir, inputFile, original, outDir, dt)
contents = strrep(original, 'simu.dt = 0.1;', ...
    sprintf('simu.dt = %.6g;', dt));
contents = strrep(contents, 'simu.pressure = 1;', ...
    'simu.pressure = 0;');
contents = strrep(contents, 'simu.paraview.option = 1;', ...
    'simu.paraview.option = 0;');
fid = fopen(inputFile, 'w');
assert(fid ~= -1, 'Could not write disposable OSWEC input');
fprintf(fid, '%s', contents);
fclose(fid);
cd(caseDir);
wecSim;
assert(simu.dt == dt && simu.nonlinearDt == dt && ...
    simu.endTime == 120 && simu.rampTime == 40 && ...
    simu.pressure == 0 && simu.paraview.option == 0 && ...
    strcmp(simu.solver, 'ode4') && ...
    strcmp(waves.type, 'regular') && waves.height == 2.5 && ...
    waves.period == 8 && body(1).nonlinearHydro == 2 && ...
    body(1).mass == 127000 && pto(1).damping == 0 && ...
    pto(1).stiffness == 0, ...
    'Refinement changed more than time step and output logging');
time = output.bodies(1).time;
pose = output.bodies(1).position;
velocity = output.bodies(1).velocity;
acceleration = output.bodies(1).acceleration;
forceExcitation = output.bodies(1).forceExcitation;
forceRadiationDamping = output.bodies(1).forceRadiationDamping;
forceAddedMass = output.bodies(1).forceAddedMass;
forceRestoring = output.bodies(1).forceRestoring;
solver = simu.solver;
nonlinearDt = simu.nonlinearDt;
assert(numel(time) == round(120 / dt) + 1 && ...
    all(isfinite([pose, velocity, acceleration, forceExcitation, ...
        forceRadiationDamping, forceAddedMass, forceRestoring]), 'all'), ...
    'Refined OSWEC output has missing or nonfinite samples');
filename = sprintf('dt-%g.mat', dt);
save(fullfile(outDir, filename), 'dt', 'time', 'pose', 'velocity', ...
    'acceleration', 'forceExcitation', 'forceRadiationDamping', ...
    'forceAddedMass', 'forceRestoring', 'solver', 'nonlinearDt', '-v7');
end
