function reference_model_baseline(model)
% Run the published RM3, OSWEC, or Sphere reference cases and save numeric output.
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
outDir = fullfile(repoRoot, 'matlab-reference-model-output');
if ~isfolder(outDir)
    mkdir(outDir);
end

if any(string(model) == ["RM3_MCR_ARRAY", "RM3_MCR_EXCEL", "RM3_MCR_MAT"])
    run_rm3_mcr_baseline(repoRoot, outDir, string(model));
    return;
end
if string(model) == "RM3_MCR_SEASTATE"
    run_rm3_mcr_seastate_baseline(repoRoot, outDir);
    return;
end

switch string(model)
    case "RM3"
        cases = string(model);
        caseDirs = string(fullfile(repoRoot, 'matlab-ref', 'examples', model));
    case "OSWEC"
        cases = string(model);
        caseDirs = string(fullfile(repoRoot, 'matlab-ref', 'examples', model));
        inputFile = fullfile(caseDirs, 'wecSimInputFile.m');
        contents = fileread(inputFile);
        oldSetting = 'waves.spread = [0.1,0.2,0.7];';
        assert(contains(contents, oldSetting), 'The pinned OSWEC input changed');
        contents = strrep(contents, oldSetting, ...
            sprintf('%s\nwaves.phaseSeed = 1;', oldSetting));
        fid = fopen(inputFile, 'w');
        assert(fid ~= -1, 'Could not seed the pinned OSWEC input');
        fprintf(fid, '%s', contents);
        fclose(fid);
    case "Sphere"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', 'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = ["0m", "1m", "1m-ME", "3m", "5m"];
        caseDirs = fullfile(repoRoot, 'applications', 'Free_Decay', cases);
    case "SPHERE_MPC"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "MPC";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Controls', 'MPC'));
    case "SPHERE_REACTIVE_DDPTO"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "ReactiveWithPTO";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Controls', 'ReactiveWithPTO'));
    case "RM3_DD_PTO"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = "RM3_DD_PTO";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'PTO-Sim', 'RM3', 'RM3_DD_PTO'));
    case {"ELLIPSOID_NLH_REG", "ELLIPSOID_NLH_CIC", ...
            "ELLIPSOID_NLH_ODE45"}
        hydroDir = fullfile(repoRoot, 'applications', 'Nonlinear_Hydro', ...
            'hydroData');
        cd(hydroDir);
        if ~isfile('ellipsoid.h5')
            bemio;
        end
        if string(model) == "ELLIPSOID_NLH_ODE45"
            cases = ["ode45_Regular", "ode45_RegularCIC"];
            caseDirs = fullfile(repoRoot, 'applications', ...
                'Nonlinear_Hydro', 'ode45', ["Regular", "RegularCIC"]);
        else
            if string(model) == "ELLIPSOID_NLH_REG"
                waveDir = "Regular";
            else
                waveDir = "RegularCIC";
            end
            cases = "ode4_" + waveDir;
            caseDirs = string(fullfile(repoRoot, 'applications', ...
                'Nonlinear_Hydro', 'ode4', waveDir));
        end
    case "SPHERE_MEAN_DRIFT"
        hydroDir = fullfile(repoRoot, 'applications', 'Mean_Drift', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "Mean_Drift";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Mean_Drift'));
    case "SPHERE_VARIABLE_MASS"
        hydroDir = fullfile(repoRoot, 'applications', 'Variable_Hydro', ...
            'Variable_Mass', 'hydroData');
        cd(hydroDir);
        if ~isfile('draft9.h5')
            bemio;
        end
        cases = "Variable_Mass";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Variable_Hydro', 'Variable_Mass'));
    case "GBM_BARGE"
        hydroDir = fullfile(repoRoot, 'applications', ...
            'Generalized_Body_Modes', 'hydroData');
        cd(hydroDir);
        if ~isfile('barge.h5')
            bemio;
        end
        cases = "Barge";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Generalized_Body_Modes'));
    case "RM3_B2B"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', 'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = ["B2B_Case1", "B2B_Case2", "B2B_Case3", "B2B_Case4"];
        caseDirs = fullfile(repoRoot, 'applications', ...
            'Body-to-Body_Interactions', cases);
    case "RM3_MOORING_MATRIX"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = "MooringMatrix";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Mooring', 'MooringMatrix'));
    case "RM3_END_STOPS"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = "End_Stops";
        caseDirs = string(fullfile(repoRoot, 'applications', 'End_Stops'));
    case {"RM3_END_STOPS_STEP", "RM3_END_STOPS_STEP_FINE", ...
            "RM3_END_STOPS_STEP_FINER", "RM3_END_STOPS_FULL_FINE", ...
            "RM3_END_STOPS_FULL_FINER"}
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        sourceDir = fullfile(repoRoot, 'applications', 'End_Stops');
        if string(model) == "RM3_END_STOPS_STEP"
            cases = "End_Stops_dt005";
            stepSize = 0.05;
        elseif string(model) == "RM3_END_STOPS_STEP_FINE"
            cases = "End_Stops_dt0025";
            stepSize = 0.025;
        elseif string(model) == "RM3_END_STOPS_STEP_FINER"
            cases = "End_Stops_dt00125";
            stepSize = 0.0125;
        elseif string(model) == "RM3_END_STOPS_FULL_FINE"
            cases = "End_Stops_dt0025_full";
            stepSize = 0.025;
        else
            cases = "End_Stops_dt00125_full";
            stepSize = 0.0125;
        end
        runEndTime = 120;
        if startsWith(string(model), "RM3_END_STOPS_FULL")
            runEndTime = 400;
        end
        caseDirs = string(fullfile(repoRoot, 'applications', cases));
        [copied, copyMessage] = copyfile(sourceDir, caseDirs);
        assert(copied, copyMessage);
        inputFile = fullfile(caseDirs, 'wecSimInputFile.m');
        contents = fileread(inputFile);
        assert(contains(contents, 'simu.dt = 0.1;') && ...
            contains(contents, 'simu.endTime = 400;'), ...
            'The pinned End_Stops time settings changed');
        contents = strrep(contents, 'simu.dt = 0.1;', ...
            sprintf('simu.dt = %.4f;', stepSize));
        contents = strrep(contents, 'simu.endTime = 400;', ...
            sprintf('simu.endTime = %d;', runEndTime));
        fid = fopen(inputFile, 'w');
        assert(fid ~= -1, 'Could not write the End_Stops step input');
        fprintf(fid, '%s', contents);
        fclose(fid);
    case "OSWEC_Nonhydro"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'OSWEC', 'hydroData');
        cd(hydroDir);
        if ~isfile('oswec.h5')
            bemio;
        end
        cases = "Nonhydro";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Nonhydro_Body'));
    case "OSWEC_MULTI_WAVE"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'OSWEC', 'hydroData');
        cd(hydroDir);
        if ~isfile('oswec.h5')
            bemio;
        end
        cases = "Multiple_Wave_Spectra";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Multiple_Wave_Spectra'));
        inputFile = fullfile(caseDirs, 'wecSimInputFile.m');
        contents = fileread(inputFile);
        sourceLines = ["waves(1).direction = 0;", ...
            "waves(2).direction = 90;"];
        seedLines = ["waves(1).phaseSeed = 1;", ...
            "waves(2).phaseSeed = 2;"];
        for iWave = 1:2
            assert(contains(contents, sourceLines(iWave)), ...
                'The pinned multiple-wave input changed');
            contents = strrep(contents, char(sourceLines(iWave)), ...
                sprintf('%s\n%s', char(sourceLines(iWave)), ...
                    char(seedLines(iWave))));
        end
        fid = fopen(inputFile, 'w');
        assert(fid ~= -1, 'Could not seed the multiple-wave input');
        fprintf(fid, '%s', contents);
        fclose(fid);
    case "OSWEC_FULL_DIR"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'OSWEC', 'hydroData');
        cd(hydroDir);
        if ~isfile('oswec.h5')
            bemio;
        end
        cases = "Full_Directional_Waves";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Full_Directional_Waves'));
    case "OSWEC_PASSIVE_YAW"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'OSWEC', 'hydroData');
        cd(hydroDir);
        if ~isfile('oswec.h5')
            bemio;
        end
        cases = ["PassiveYawOFF", "PassiveYawON"];
        caseDirs = fullfile(repoRoot, 'applications', 'Passive_Yaw', cases);
    case {"OSWEC_PASSIVE_YAW_IRR", "OSWEC_PASSIVE_YAW_IRR_CONT"}
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'OSWEC', 'hydroData');
        cd(hydroDir);
        if ~isfile('oswec.h5')
            bemio;
        end
        sourceDir = fullfile(repoRoot, 'applications', 'Passive_Yaw', ...
            'PassiveYawRegression');
        if string(model) == "OSWEC_PASSIVE_YAW_IRR_CONT"
            cases = "PassiveYawRegressionContinuous";
            caseDirs = string(fullfile(repoRoot, 'applications', ...
                'Passive_Yaw', cases));
            [copied, copyMessage] = copyfile(sourceDir, caseDirs);
            assert(copied, copyMessage);
            inputFile = fullfile(caseDirs, 'wecSimInputFile.m');
            contents = fileread(inputFile);
            for iBody = 1:2
                oldSetting = sprintf('body(%d).yaw.threshold = 1;', iBody);
                newSetting = sprintf('body(%d).yaw.threshold = 0;', iBody);
                assert(contains(contents, oldSetting), ...
                    'The pinned passive-yaw threshold changed');
                contents = strrep(contents, oldSetting, newSetting);
            end
            fid = fopen(inputFile, 'w');
            assert(fid ~= -1, 'Could not write the continuous-yaw input');
            fprintf(fid, '%s', contents);
            fclose(fid);
        else
            cases = "PassiveYawRegression";
            caseDirs = string(sourceDir);
        end
    case "RM3_PTO_Extension"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = ["float", "spar"];
        caseDirs = fullfile(repoRoot, 'applications', ...
            'RM3_PTO_Extension', cases);
    case "RM3_Radiation_Options"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        cases = ["constant", "FIR", "state_space", "convolution"];
        caseDirs = repmat(string(fullfile(repoRoot, 'applications', ...
            'Radiation_Force_Options')), size(cases));
    case "RM3_MCR"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', 'RM3', 'hydroData');
        cd(hydroDir);
        if ~isfile('rm3.h5')
            bemio;
        end
        sourceDir = fullfile(repoRoot, 'applications', 'Multiple_Condition_Runs', 'RM3_MCROPT1');
        cases = strings(1, 8);
        caseDirs = strings(1, 8);
        iCase = 0;
        for damping = [1200000, 2400000]
            for period = [6, 8]
                for height = [1.5, 2.5]
                    iCase = iCase + 1;
                    cases(iCase) = sprintf('H%d_T%d_D%d', ...
                        round(10 * height), period, round(damping / 100000));
                    caseDirs(iCase) = fullfile(repoRoot, 'applications', ...
                        'Multiple_Condition_Runs', 'paired_' + cases(iCase));
                    [copied, copyMessage] = copyfile(sourceDir, caseDirs(iCase));
                    assert(copied, copyMessage);
                    inputFile = fullfile(caseDirs(iCase), 'wecSimInputFile.m');
                    contents = fileread(inputFile);
                    oldSettings = ["waves.height = 1.5:1:2.5;", ...
                        "waves.period = 6:2:8;", ...
                        "pto(1).damping=1200000:1200000:2400000;"];
                    newSettings = ["waves.height = " + string(height) + ";", ...
                        "waves.period = " + string(period) + ";", ...
                        "pto(1).damping=" + string(damping) + ";"];
                    for iSetting = 1:numel(oldSettings)
                        assert(contains(contents, oldSettings(iSetting)), ...
                            'The pinned RM3 MCR input changed');
                        contents = strrep(contents, char(oldSettings(iSetting)), ...
                            char(newSettings(iSetting)));
                    end
                    fid = fopen(inputFile, 'w');
                    assert(fid ~= -1, 'Could not write the RM3 MCR input');
                    fprintf(fid, '%s', contents);
                    fclose(fid);
                end
            end
        end
    case "Sphere_Passive"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', 'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "Passive_P";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Controls', 'Passive (P)'));
    case "Sphere_PTO_Config"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', 'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        sourceDir = fullfile(repoRoot, 'applications', 'Controls', 'Passive (P)');
        caseDir = fullfile(repoRoot, 'applications', 'Controls', 'Passive_Config');
        [copied, copyMessage] = copyfile(sourceDir, caseDir);
        assert(copied, copyMessage);
        inputFile = fullfile(caseDir, 'wecSimInputFile.m');
        contents = fileread(inputFile);
        oldSettings = ["pto(1).stiffness = 0;", "pto(1).damping = 0;", ...
            "pto(1).location = [0 0 0];"];
        newSettings = ["pto(1).stiffness = 50000;", ...
            "pto(1).damping = 100000;", "pto(1).location = [1 0 0];"];
        for iSetting = 1:numel(oldSettings)
            assert(contains(contents, oldSettings(iSetting)), ...
                'The pinned passive-controller input changed');
            contents = strrep(contents, char(oldSettings(iSetting)), ...
                char(newSettings(iSetting)));
        end
        fid = fopen(inputFile, 'w');
        assert(fid ~= -1, 'Could not write the configured PTO input');
        fprintf(fid, '%s', contents);
        fclose(fid);
        cases = "Configured";
        caseDirs = string(caseDir);
    case "Sphere_Reactive_PI"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "Reactive_PI";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Controls', ...
            'Reactive (PI)'));
    case "Sphere_Declutching"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "Declutching";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Controls', ...
            'Declutching'));
    case "Sphere_Latching"
        hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
            'Sphere', 'hydroData');
        cd(hydroDir);
        if ~isfile('sphere.h5')
            bemio;
        end
        cases = "Latching";
        caseDirs = string(fullfile(repoRoot, 'applications', 'Controls', ...
            'Latching'));
    case "MORISON_FIXED"
        cases = "morisonElement";
        caseDirs = string(fullfile(repoRoot, 'applications', ...
            'Morison_Element', cases));
    otherwise
        error('Unknown reference model: %s', model);
end

for iCase = 1:numel(cases)
    cd(caseDirs(iCase));
    if string(model) == "SPHERE_MPC"
        instrument_sphere_mpc();
    end
    if string(model) == "RM3_Radiation_Options"
        [output, simu] = run_radiation_option(cases(iCase));
    else
        wecSim;
    end
    assert(exist('output', 'var') == 1 && ~isempty(output.bodies), ...
        'The MATLAB case produced no body output');
    if string(model) == "SPHERE_MPC"
        cfg = controller(1).modelPredictiveControl;
        assert(strcmp(simu.solver, 'ode4') && simu.dt == 0.01 && ...
            simu.endTime == 400 && simu.rampTime == 100 && ...
            strcmp(waves.type, 'irregular') && ...
            strcmp(waves.spectrumType, 'JS') && ...
            waves.height == 2.5 && waves.period == 8 && ...
            waves.phaseSeed == 1 && ...
            cfg.maxPTOForce == 2e6 && cfg.maxPTOForceChange == 1.5e6 && ...
            cfg.maxPos == 4 && cfg.maxVel == 3 && ...
            cfg.predictionHorizon == 15 && cfg.dt == 0.5 && ...
            controller(1).MPC == 1, ...
            'The pinned Sphere MPC settings changed');
        assert(exist('controller1_out', 'var') == 1 && ...
            size(controller1_out.signals.values, 2) == 12, ...
            'Sphere MPC controller output is missing');
        writematrix([waves.omega(:), waves.amplitude(:), ...
            waves.dOmega(:), waves.phase(:)], ...
            fullfile(outDir, 'SPHERE_MPC_components.csv'));
        writematrix(waves.waveAmpTime, ...
            fullfile(outDir, 'SPHERE_MPC_wave.csv'));
        setup = controller(1).MPCSetup;
        plant = controller(1).plant;
        if isfield(plant, 'sys_c')
            plant = rmfield(plant, 'sys_c');
        end
        save(fullfile(outDir, 'SPHERE_MPC_setup.mat'), 'setup', 'plant');
        assert(exist('plantOutput', 'var') == 1 && ...
            isa(plantOutput, 'timeseries'), ...
            'Sphere MPC prediction-plant output is missing');
        plantTime = plantOutput.Time(:);
        plantValues = squeeze(plantOutput.Data);
        if size(plantValues, 1) ~= numel(plantTime)
            plantValues = plantValues.';
        end
        assert(size(plantValues, 1) == numel(plantTime) && ...
            size(plantValues, 2) == 3, ...
            'Sphere MPC prediction-plant signal changed');
        writematrix([plantTime, plantValues], ...
            fullfile(outDir, 'SPHERE_MPC_plant_output.csv'));
        export_mpc_trace(outDir, 'SPHERE_MPC_full_state.csv', ...
            mpcFullState, 9);
        export_mpc_trace(outDir, 'SPHERE_MPC_excitation_prediction.csv', ...
            mpcExcitationPrediction, 31);
        export_mpc_trace(outDir, 'SPHERE_MPC_command_rate.csv', ...
            mpcCommandRate, 1);
        export_mpc_trace(outDir, 'SPHERE_MPC_iteration.csv', ...
            mpcIteration, 1);
    end
    if string(model) == "GBM_BARGE"
        assert(exist('Flex_out', 'var') == 1 && isstruct(Flex_out) && ...
            isfield(Flex_out, 'signals') && isfield(Flex_out, 'time'), ...
            'The published flexible-body output is missing');
        save(fullfile(outDir, 'GBM_BARGE_Flex_out.mat'), 'Flex_out');
        writematrix(size(Flex_out.signals.values), fullfile(outDir, ...
            'GBM_BARGE_Flex_out_dimensions.csv'));
        assert(strcmp(simu.solver, 'ode45') && simu.dt == 0.05 && ...
            simu.endTime == 400 && simu.rampTime == 100 && ...
            strcmp(waves.type, 'regular') && waves.height == 2 && ...
            waves.period == 8 && body(1).dof > 6 && ...
            body(1).gbmDOF == body(1).dof - 6 && body(1).flex == 1, ...
            'The pinned generalized-body-mode case changed');
        gbm = body(1).hydroForce.hf1.gbm;
        writematrix(gbm.mass_ff, fullfile(outDir, ...
            'GBM_BARGE_flexible_effective_mass.csv'));
        writematrix(gbm.stiffness, fullfile(outDir, ...
            'GBM_BARGE_flexible_stiffness.csv'));
        writematrix(gbm.damping, fullfile(outDir, ...
            'GBM_BARGE_flexible_damping.csv'));
        writematrix(body(1).hydroForce.hf1.fAddedMass, ...
            fullfile(outDir, 'GBM_BARGE_added_mass.csv'));
        writematrix(body(1).hydroForce.hf1.fDamping, ...
            fullfile(outDir, 'GBM_BARGE_radiation_damping.csv'));
        writematrix([body(1).hydroForce.hf1.fExt.re(:), ...
            body(1).hydroForce.hf1.fExt.im(:)], ...
            fullfile(outDir, 'GBM_BARGE_excitation_coefficients.csv'));
        writematrix(body(1).hydroForce.hf1.linearHydroRestCoef, ...
            fullfile(outDir, 'GBM_BARGE_hydrostatic_stiffness.csv'));
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, 'GBM_BARGE_wave.csv'));
        writecell(fieldnames(output.bodies(1)), fullfile(outDir, ...
            'GBM_BARGE_body_fields.txt'));
    end
    if any(string(model) == ["RM3_END_STOPS", "RM3_END_STOPS_STEP", ...
                             "RM3_END_STOPS_STEP_FINE", ...
                             "RM3_END_STOPS_STEP_FINER", ...
                             "RM3_END_STOPS_FULL_FINE", ...
                             "RM3_END_STOPS_FULL_FINER"])
        stops = pto(1).hardStops;
        assert(strcmp(stops.upperLimitSpecify, 'on') && ...
            strcmp(stops.lowerLimitSpecify, 'on') && ...
            stops.upperLimitBound == 0.6 && stops.lowerLimitBound == -0.6 && ...
            stops.upperLimitStiffness == 1e8 && ...
            stops.lowerLimitStiffness == 1e8 && ...
            stops.upperLimitDamping == 0 && stops.lowerLimitDamping == 0 && ...
            stops.upperLimitTransitionRegionWidth == 1e-4 && ...
            stops.lowerLimitTransitionRegionWidth == 1e-4, ...
            'The pinned End_Stops effective hard-stop settings changed');
        writematrix([stops.lowerLimitBound, stops.upperLimitBound, ...
            stops.lowerLimitStiffness, stops.upperLimitStiffness, ...
            stops.lowerLimitDamping, stops.upperLimitDamping, ...
            stops.lowerLimitTransitionRegionWidth, ...
            stops.upperLimitTransitionRegionWidth], ...
            fullfile(outDir, string(model) + "_settings.csv"));
        if any(string(model) == ["RM3_END_STOPS_STEP", ...
                                 "RM3_END_STOPS_STEP_FINE", ...
                                 "RM3_END_STOPS_STEP_FINER", ...
                                 "RM3_END_STOPS_FULL_FINE", ...
                                 "RM3_END_STOPS_FULL_FINER"])
            assert(simu.dt == stepSize && simu.endTime == runEndTime, ...
                'The End_Stops step diagnostic did not use its requested settings');
            writematrix([simu.dt, simu.endTime, simu.rampTime], ...
                fullfile(outDir, string(model) + "_run_settings.csv"));
        end
    end
    if string(model) == "OSWEC"
        % The published case shuffles its random phase. The baseline sets
        % phaseSeed=1 and saves the realized components for paired checks.
        assert(waves.phaseSeed == 1, 'OSWEC phase seed was not applied');
        components = [waves.omega(:), waves.amplitude(:), ...
            waves.dOmega(:), waves.phase];
        assert(all(isfinite(components), 'all'), 'Nonfinite wave components');
        writematrix(components, fullfile(outDir, 'OSWEC_wave_components.csv'));
        writematrix([waves.direction(:), waves.spread(:)], ...
            fullfile(outDir, 'OSWEC_wave_directions.csv'));
        writematrix(waves.waveAmpTime, fullfile(outDir, 'OSWEC_wave_elevation.csv'));
    end
    if string(model) == "MORISON_FIXED"
        assert(strcmp(simu.solver, 'ode4') && simu.dt == 0.01 && ...
            simu.endTime == 400 && simu.rampTime == 100 && ...
            simu.rho == 1025 && strcmp(waves.type, 'irregular') && ...
            strcmp(waves.spectrumType, 'PM') && ...
            waves.height == 2 && waves.period == 5 && ...
            waves.phaseSeed == 5 && ...
            isequal(waves.direction, [0 30 90]) && ...
            isequal(waves.spread, [0.1 0.2 0.7]) && ...
            isequal(waves.bem.range, [0.001 10]) && ...
            waves.waterDepth == 30 && ...
            body(1).nonHydro == 2 && body(2).nonHydro == 1 && ...
            body(1).morisonElement.option == 1 && ...
            isequal(body(1).morisonElement.cd, [1 1 1]) && ...
            isequal(body(1).morisonElement.ca, [1 1 1]) && ...
            isequal(body(1).morisonElement.area, ...
                [300 300 pi*10^2/4]) && ...
            body(1).morisonElement.VME == pi*10^2*30 && ...
            isequal(body(1).morisonElement.rgME, [0 0 10]) && ...
            isequal(body(1).centerGravity, [0 0 -15]) && ...
            isequal(body(2).centerGravity, [0 0 25]) && ...
            isequal(constraint(1).location, [0 0 0]) && ...
            isequal(constraint(2).location, [0 0 -30]), ...
            'The pinned fixed Morison-element input changed');
        components = [waves.omega(:), waves.amplitude(:), ...
            waves.dOmega(:), waves.wavenumber(:), waves.phase];
        assert(size(components, 2) == 7 && ...
            all(isfinite(components), 'all'), ...
            'The fixed Morison wave components are incomplete');
        writematrix(components, fullfile(outDir, ...
            'MORISON_FIXED_components.csv'));
        writematrix([waves.direction(:), waves.spread(:)], ...
            fullfile(outDir, 'MORISON_FIXED_directions.csv'));
        writematrix(waves.waveAmpTime, fullfile(outDir, ...
            'MORISON_FIXED_wave.csv'));
    end
    if string(model) == "SPHERE_VARIABLE_MASS"
        assert(simu.dt == 0.01 && simu.dtOut == 0.1 && ...
            simu.endTime == 900 && simu.rho == 1025 && ...
            strcmp(simu.solver, 'ode4') && ...
            strcmp(waves.type, 'regular') && waves.height == 1 && ...
            waves.period == 8 && pto(1).damping == 2e5 && ...
            body(1).variableHydro.option == 1 && ...
            numel(body(1).h5File) == 9 && ...
            isequal(body(1).variableHydro.mass, massVals), ...
            'The pinned variable-mass input changed');
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, 'SPHERE_VARIABLE_MASS_wave.csv'));
        writematrix([(1:9)', draftVals(:), massVals(:), inertiaVals], ...
            fullfile(outDir, 'SPHERE_VARIABLE_MASS_states.csv'));
        writematrix([(0:900)', min(floor((0:900)'/100) + 1, 9)], ...
            fullfile(outDir, 'SPHERE_VARIABLE_MASS_schedule.csv'));
    end
    if string(model) == "SPHERE_REACTIVE_DDPTO"
        drive = ptoSim(1).simpleDirectDrivePTO;
        assert(strcmp(simu.solver, 'ode45') && simu.dt == 0.01 && ...
            simu.endTime == 200 && simu.rampTime == 50 && ...
            strcmp(waves.type, 'regular') && waves.height == 2.5 && ...
            waves.period == 9.6664 && ...
            pto(1).stiffness == 0 && pto(1).damping == 0 && ...
            controller(1).proportionalIntegral.Kp == 3.8e5 && ...
            controller(1).proportionalIntegral.Ki == -1.52e5 && ...
            drive.torqueConstant == 7.186 && drive.gearRatio == 100 && ...
            drive.drivetrainInertia == 2 && ...
            drive.drivetrainFriction == 1 && ...
            drive.windingResistance == 0.483 && ...
            drive.windingInductance == 5.223e-3, ...
            'The pinned reactive direct-drive input changed');
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, 'SPHERE_REACTIVE_DDPTO_wave.csv'));
        writematrix([body(1).mass, body(1).inertia, ...
            body(1).hydroForce.hf1.adjustedMass], ...
            fullfile(outDir, 'SPHERE_REACTIVE_DDPTO_mass.csv'));
        assert(isfield(output.ptoSim, 'time') && ...
            isfield(output.ptoSim, 'elecPower'), ...
            'The direct-drive PTO produced no output');
        driveOutput = output.ptoSim(1);
        driveValues = [driveOutput.time(:), driveOutput.velocity(:), ...
            driveOutput.absPower(:), driveOutput.force(:), ...
            driveOutput.inertiaForce(:), driveOutput.fricForce(:), ...
            driveOutput.genForce(:), driveOutput.current(:), ...
            driveOutput.voltage(:), driveOutput.I2RLosses(:), ...
            driveOutput.elecPower(:)];
        assert(all(isfinite(driveValues), 'all'), ...
            'The direct-drive PTO output is nonfinite');
        writematrix(driveValues, ...
            fullfile(outDir, 'SPHERE_REACTIVE_DDPTO_drive.csv'));
    end
    if string(model) == "RM3_DD_PTO"
        generator = ptoSim(1).directLinearGenerator;
        assert(strcmp(simu.solver, 'ode4') && simu.dt == 0.0005 && ...
            simu.dtOut == 0.0005 && simu.endTime == 400 && ...
            simu.rampTime == 100 && ...
            strcmp(waves.type, 'regular') && waves.height == 2.5 && ...
            waves.period == 8 && pto(1).stiffness == 0 && ...
            pto(1).damping == 0 && ptoSim(1).typeNum == 9 && ...
            generator.Rs == 4.58 && generator.Bfric == -100 && ...
            generator.tau_p == 0.072 && generator.lambda_fd == 8 && ...
            generator.Ls == 0.285 && generator.Rload == -117.6471 && ...
            generator.theta_d_0 == 0 && ...
            generator.lambda_sq_0 == 0 && ...
            generator.lambda_sd_0 == 8, ...
            'The pinned RM3 direct linear generator settings changed');
        assert(isfield(output.ptoSim, 'Ia') && ...
            isfield(output.ptoSim, 'elecPower'), ...
            'The RM3 direct linear generator produced no output');
        driveOutput = output.ptoSim(1);
        driveValues = [driveOutput.time(:), driveOutput.absPower(:), ...
            driveOutput.force(:), driveOutput.fricForce(:), ...
            driveOutput.Ia(:), driveOutput.Ib(:), driveOutput.Ic(:), ...
            driveOutput.Va(:), driveOutput.Vb(:), driveOutput.Vc(:), ...
            driveOutput.vel(:), driveOutput.elecPower(:)];
        driveValues = driveValues(1:20:end, :);
        assert(size(driveValues, 2) == 12 && ...
            all(isfinite(driveValues), 'all'), ...
            'The RM3 direct linear generator output is nonfinite');
        writematrix(driveValues, ...
            fullfile(outDir, 'RM3_DD_PTO_drive.csv'));
    end
    if any(string(model) == ["ELLIPSOID_NLH_REG", "ELLIPSOID_NLH_CIC", ...
            "ELLIPSOID_NLH_ODE45"])
        if string(cases(iCase)) == "ode4_Regular" || ...
                string(cases(iCase)) == "ode45_Regular"
            waveType = 'regular';
        else
            waveType = 'regularCIC';
        end
        if string(model) == "ELLIPSOID_NLH_ODE45"
            assert(strcmp(simu.solver, 'ode45'), ...
                'The pinned nonlinear-hydro solver changed');
            prefix = string(model) + "_" + cases(iCase);
        else
            prefix = string(model);
        end
        assert(simu.dt == 0.05 && simu.endTime == 150 && ...
            simu.rampTime == 50 && simu.rho == 1025 && ...
            strcmp(waves.type, waveType) && waves.height == 4 && ...
            waves.period == 6 && body(1).nonlinearHydro == 2 && ...
            pto(1).damping == 1200000 && ...
            isequal(constraint(1).location, [0 0 -12.5]), ...
            'The pinned nonlinear-hydro input changed');
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, prefix + '_wave.csv'));
        writematrix([body(1).mass, body(1).inertia], ...
            fullfile(outDir, prefix + '_mass.csv'));
    end
    if string(model) == "OSWEC_MULTI_WAVE"
        assert(simu.dt == 0.1 && simu.endTime == 100 && ...
            simu.rampTime == 0.1 && simu.cicEndTime == 40 && ...
            numel(waves) == 2 && ...
            all([waves.height] == [2 1]) && ...
            all([waves.period] == [3 3]) && ...
            all([waves.direction] == [0 90]) && ...
            all([waves.phaseSeed] == [1 2]) && ...
            body(1).mass == 12700 && body(1).yaw.option == 1 && ...
            body(2).yaw.option == 1 && ...
            body(1).yaw.threshold == 0.01 && ...
            body(2).yaw.threshold == 0.01 && ...
            pto(1).damping == 120000 && ...
            isequal(pto(1).location, [0 0 -8.9]) && ...
            isequal(constraint(1).location, [0 0 -10]), ...
            'The pinned multiple-wave settings changed');
        for iWave = 1:2
            components = [waves(iWave).omega(:), ...
                waves(iWave).amplitude(:), waves(iWave).dOmega(:), ...
                waves(iWave).phase(:)];
            assert(size(components, 2) == 4 && ...
                all(isfinite(components), 'all'), ...
                'The multiple-wave components are invalid');
            writematrix(components, fullfile(outDir, sprintf( ...
                'OSWEC_MULTI_WAVE_wave%d_components.csv', iWave)));
            writematrix(waves(iWave).waveAmpTime, ...
                fullfile(outDir, sprintf( ...
                'OSWEC_MULTI_WAVE_wave%d_elevation.csv', iWave)));
        end
        writematrix([body(1).mass, body(1).inertia, ...
            body(1).yaw.option, body(1).yaw.threshold, ...
            pto(1).damping, pto(1).stiffness], ...
            fullfile(outDir, 'OSWEC_MULTI_WAVE_settings.csv'));
    end
    if string(model) == "OSWEC_FULL_DIR"
        assert(simu.dt == 0.05 && simu.endTime == 400 && ...
            simu.rampTime == 100 && simu.cicEndTime == 30 && ...
            strcmp(waves.type, 'spectrumImportFullDir') && ...
            waves.phaseSeed == 1 && body(1).mass == 127000 && ...
            body(2).mass == 999 && pto(1).damping == 12000 && ...
            isequal(pto(1).location, [0 0 -8.9]) && ...
            isequal(constraint(1).location, [0 0 -10]), ...
            'The pinned full-directional settings changed');
        assert(size(waves.phase, 2) == numel(waves.fullDirectionalSpectrum.directions) ...
            && isequal(size(waves.phase), size(waves.amplitude)) && ...
            all(isfinite(waves.phase), 'all') && ...
            all(isfinite(waves.amplitude), 'all'), ...
            'The full-directional realization is invalid');
        writematrix([waves.omega(:), waves.dOmega(:), ...
            waves.fullDirectionalSpectrum.spectrum(:)], ...
            fullfile(outDir, 'OSWEC_FULL_DIR_frequency.csv'));
        writematrix([waves.fullDirectionalSpectrum.directions(:), ...
            waves.dTheta(:)], ...
            fullfile(outDir, 'OSWEC_FULL_DIR_directions.csv'));
        writematrix(waves.fullDirectionalSpectrum.spread, ...
            fullfile(outDir, 'OSWEC_FULL_DIR_spread.csv'));
        writematrix(waves.amplitude, ...
            fullfile(outDir, 'OSWEC_FULL_DIR_amplitude.csv'));
        writematrix(waves.phase, ...
            fullfile(outDir, 'OSWEC_FULL_DIR_phase.csv'));
        writematrix(waves.waveAmpTime, ...
            fullfile(outDir, 'OSWEC_FULL_DIR_wave.csv'));
    end
    if string(model) == "OSWEC_PASSIVE_YAW"
        assert(simu.dt == 0.01 && simu.endTime == 600 && ...
            simu.rampTime == 100 && simu.cicEndTime == 40 && ...
            strcmp(waves.type, 'regular') && waves.height == 2.5 && ...
            waves.period == 8 && waves.direction == 10 && ...
            body(1).mass == 12700 && body(2).mass == 999 && ...
            body(1).yaw.option == iCase - 1 && ...
            body(2).yaw.option == iCase - 1 && ...
            pto(1).damping == 120000 && ...
            isequal(pto(1).location, [0 0 -8.9]) && ...
            isequal(constraint(1).location, [0 0 -10]), ...
            'The pinned passive-yaw settings changed');
        if iCase == 2
            assert(body(1).yaw.threshold == 0.01 && ...
                body(2).yaw.threshold == 0.01, ...
                'The pinned passive-yaw threshold changed');
        end
        writematrix(waves.waveAmpTime, fullfile(outDir, sprintf( ...
            'OSWEC_PASSIVE_YAW_%s_wave.csv', cases(iCase))));
    end
    if any(string(model) == ["OSWEC_PASSIVE_YAW_IRR", ...
                             "OSWEC_PASSIVE_YAW_IRR_CONT"])
        expectedThreshold = double(string(model) == "OSWEC_PASSIVE_YAW_IRR");
        assert(simu.dt == 0.01 && simu.endTime == 250 && ...
            simu.rampTime == 100 && simu.cicEndTime == 40 && ...
            strcmp(waves.type, 'irregular') && waves.height == 2.5 && ...
            waves.period == 8 && waves.direction == 10 && ...
            waves.phaseSeed == 1 && strcmp(waves.spectrumType, 'PM') && ...
            body(1).mass == 12700 && body(2).mass == 999 && ...
            body(1).yaw.option == 1 && body(2).yaw.option == 1 && ...
            body(1).yaw.threshold == expectedThreshold && ...
            body(2).yaw.threshold == expectedThreshold && ...
            pto(1).damping == 120000 && ...
            isequal(pto(1).location, [0 0 -8.9]) && ...
            isequal(constraint(1).location, [0 0 -10]), ...
            'The pinned irregular passive-yaw settings changed');
        components = [waves.omega(:), waves.amplitude(:), ...
            waves.dOmega(:), waves.phase(:)];
        assert(size(components, 2) == 4 && ...
            all(isfinite(components), 'all'), ...
            'The irregular passive-yaw components are invalid');
        writematrix(components, fullfile(outDir, ...
            sprintf('%s_components.csv', model)));
        writematrix(waves.waveAmpTime, fullfile(outDir, ...
            sprintf('%s_wave.csv', model)));
    end
    if string(model) == "RM3_MOORING_MATRIX"
        assert(simu.dt == 0.01 && simu.endTime == 400 && ...
            strcmp(waves.type, 'elevationImport'), ...
            'The pinned RM3 mooring wave or time settings changed');
        stiffness = mooring(1).matrix.stiffness;
        damping = mooring(1).matrix.damping;
        pretension = mooring(1).matrix.preTension;
        assert(isequal(size(stiffness), [6, 6]) && ...
            stiffness(1, 1) == 1e5 && nnz(stiffness) == 1 && ...
            ~any(damping, 'all') && ~any(pretension), ...
            'The pinned RM3 mooring matrix changed');
        assert(isstruct(output.mooring) && ...
            isfield(output.mooring, 'forceMooring'), ...
            'The RM3 mooring force was not logged');
        mooringOutput = output.mooring(1);
        mooringValues = [mooringOutput.time(:), mooringOutput.position, ...
            mooringOutput.velocity, mooringOutput.forceMooring];
        assert(size(mooringValues, 2) == 19 && ...
            all(isfinite(mooringValues), 'all'), ...
            'The RM3 mooring response is incomplete');
        writematrix(mooringValues, fullfile(outDir, ...
            'RM3_MOORING_MATRIX_mooring1.csv'));
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, 'RM3_MOORING_MATRIX_wave.csv'));
        writematrix(stiffness, fullfile(outDir, ...
            'RM3_MOORING_MATRIX_stiffness.csv'));
    end
    if string(model) == "SPHERE_MEAN_DRIFT"
        assert(simu.dt == 0.01 && simu.endTime == 100 && ...
            simu.rampTime == 20 && strcmp(waves.type, 'regularCIC') && ...
            waves.height == 0.1 && waves.period == 2 && ...
            body(1).meanDrift == 1, ...
            'The pinned Sphere mean-drift settings changed');
        assert(isfield(body(1).hydroForce.hf1.fExt, 'md') && ...
            any(body(1).hydroForce.hf1.fExt.md ~= 0), ...
            'The source mean-drift excitation is absent');
        writematrix([body(1).hydroForce.hf1.fExt.re(:), ...
            body(1).hydroForce.hf1.fExt.im(:), ...
            body(1).hydroForce.hf1.fExt.md(:)], ...
            fullfile(outDir, 'SPHERE_MEAN_DRIFT_excitation_coefficients.csv'));
        writematrix([output.wave.time(:), output.wave.elevation(:)], ...
            fullfile(outDir, 'SPHERE_MEAN_DRIFT_wave.csv'));
        writematrix([body(1).mass, body(1).inertia], ...
            fullfile(outDir, 'SPHERE_MEAN_DRIFT_mass_properties.csv'));
    end
    for iBody = 1:numel(output.bodies)
        response = output.bodies(iBody);
        values = [response.time(:), response.position, response.velocity, ...
            response.forceTotal, response.forceExcitation];
        if string(model) == "MORISON_FIXED" && iBody == 1
            morisonForce = [response.time(:), ...
                response.forceMorisonAndViscous];
            assert(size(morisonForce, 2) == 7 && ...
                all(isfinite(morisonForce), 'all') && ...
                any(abs(morisonForce(:, 2:7)) > 0, 'all'), ...
                'The fixed Morison-element force is missing');
            writematrix(morisonForce, fullfile(outDir, ...
                'MORISON_FIXED_morison_force.csv'));
        end
        if string(model) == "OSWEC_PASSIVE_YAW_IRR" && iBody == 1
            yawForces = [response.time(:), ...
                response.forceRadiationDamping, response.forceAddedMass, ...
                response.forceRestoring, response.acceleration];
            assert(size(yawForces, 2) == 25 && ...
                all(isfinite(yawForces), 'all'), ...
                'Irregular passive-yaw force diagnostics are incomplete');
            writematrix(yawForces, fullfile(outDir, ...
                'OSWEC_PASSIVE_YAW_IRR_body1_forces.csv'));
            writematrix([body(iBody).mass, body(iBody).inertia], ...
                fullfile(outDir, ...
                'OSWEC_PASSIVE_YAW_IRR_body1_mass.csv'));
        end
        if any(string(model) == ["RM3_END_STOPS", "RM3_END_STOPS_STEP", ...
                                 "RM3_END_STOPS_STEP_FINE", ...
                                 "RM3_END_STOPS_STEP_FINER", ...
                                 "RM3_END_STOPS_FULL_FINE", ...
                                 "RM3_END_STOPS_FULL_FINER"])
            forceValues = [response.time(:), response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring, ...
                response.acceleration];
            assert(all(isfinite(forceValues), 'all'), ...
                'End-stop hydrodynamic forces contain nonfinite values');
            writematrix(forceValues, fullfile(outDir, sprintf( ...
                '%s_body%d_forces.csv', model, iBody)));
            hydroForce = body(iBody).hydroForce.hf1;
            assert(isfield(hydroForce.storage, 'hydroForce_fAddedMass'), ...
                'End-stop case is missing its applied added-mass matrix');
            writematrix(hydroForce.fAddedMass, fullfile(outDir, sprintf( ...
                '%s_body%d_added_mass_original.csv', model, iBody)));
            writematrix(hydroForce.storage.hydroForce_fAddedMass, ...
                fullfile(outDir, sprintf( ...
                '%s_body%d_added_mass_applied.csv', model, iBody)));
            properties = [body(iBody).mass, hydroForce.mass, ...
                hydroForce.adjustedMass, body(iBody).inertia, ...
                hydroForce.adjustedInertia];
            writematrix(properties, fullfile(outDir, sprintf( ...
                '%s_body%d_mass_properties.csv', model, iBody)));
        end
        if string(model) == "RM3_Radiation_Options"
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass];
        end
        if string(model) == "SPHERE_MEAN_DRIFT"
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring];
        end
        if string(model) == "SPHERE_VARIABLE_MASS"
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring, ...
                response.acceleration];
            writematrix([response.time(:), ...
                response.hydroForceIndex(:)], ...
                fullfile(outDir, 'SPHERE_VARIABLE_MASS_active_state.csv'));
        end
        if string(model) == "SPHERE_REACTIVE_DDPTO"
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring, ...
                response.acceleration];
        end
        if string(model) == "GBM_BARGE"
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring, ...
                response.acceleration];
            writematrix([size(response.position, 2), ...
                size(response.velocity, 2), ...
                size(response.forceTotal, 2), ...
                size(response.forceExcitation, 2), ...
                size(response.acceleration, 2)], ...
                fullfile(outDir, 'GBM_BARGE_output_dimensions.csv'));
        end
        if any(string(model) == ["ELLIPSOID_NLH_REG", "ELLIPSOID_NLH_CIC", ...
                "ELLIPSOID_NLH_ODE45"])
            values = [values, response.forceRadiationDamping, ...
                response.forceAddedMass, response.forceRestoring, ...
                response.forceMorisonAndViscous, response.acceleration];
        end
        assert(all(isfinite(values), 'all'), 'The MATLAB response contains nonfinite values');
        if string(model) == "RM3_DD_PTO"
            values = values(1:20:end, :);
        end
        filename = sprintf('%s_%s_body%d.csv', model, cases(iCase), iBody);
        writematrix(values, fullfile(outDir, filename));
    end
    if ismember(string(model), ["Sphere_Passive", "Sphere_PTO_Config", ...
            "Sphere_Reactive_PI", "Sphere_Declutching", "Sphere_Latching", ...
            "SPHERE_REACTIVE_DDPTO", "SPHERE_MPC"])
        assert(exist('controller1_out', 'var') == 1, ...
            'The Sphere controller produced no logged output');
        controllerValues = [controller1_out.time(:), controller1_out.signals.values];
        assert(size(controllerValues, 2) == 13, ...
            'Expected six force and six power components from Sphere controller');
        assert(all(isfinite(controllerValues), 'all'), ...
            'The passive controller output contains nonfinite values');
        writematrix(controllerValues, fullfile(outDir, string(model) + "_controller.csv"));
    end
    if isstruct(output.ptos) && isfield(output.ptos, 'time')
        for iPto = 1:numel(output.ptos)
            response = output.ptos(iPto);
            values = [response.time(:), response.position, response.velocity, ...
                response.forceInternalMechanics, response.powerInternalMechanics];
            if any(string(model) == ["RM3_END_STOPS", "RM3_END_STOPS_STEP", ...
                                     "RM3_END_STOPS_STEP_FINE", ...
                                     "RM3_END_STOPS_STEP_FINER", ...
                                     "RM3_END_STOPS_FULL_FINE", ...
                                     "RM3_END_STOPS_FULL_FINER"])
                values = [values, response.forceTotal, ...
                    response.forceConstraint, response.forceActuation, ...
                    response.acceleration];
            end
            assert(all(isfinite(values), 'all'), 'The MATLAB PTO response contains nonfinite values');
            if string(model) == "RM3_DD_PTO"
                values = values(1:20:end, :);
            end
            filename = sprintf('%s_%s_pto%d.csv', model, cases(iCase), iPto);
            writematrix(values, fullfile(outDir, filename));
        end
    end
    close_system(erase(simu.simMechanicsFile, '.slx'), 0);
    clear output;
end
end

function [output, simu] = run_radiation_option(option)
% Isolate each published radiation option's script workspace.
enable_convolution = 0;
enable_FIR = 0;
enable_ss = 0;
switch option
    case "constant"
        enable_convolution = 0;
    case "FIR"
        enable_FIR = 1;
    case "state_space"
        enable_ss = 1;
    case "convolution"
        enable_convolution = 1;
    otherwise
        error('Unknown RM3 radiation option: %s', option);
end
wecSim;
end

function run_rm3_mcr_baseline(repoRoot, outDir, model)
% Execute each pinned RM3 MCR driver, including its postprocessing.
switch model
    case "RM3_MCR_ARRAY"
        folder = 'RM3_MCROPT1';
    case "RM3_MCR_EXCEL"
        folder = 'RM3_MCROPT2';
    case "RM3_MCR_MAT"
        folder = 'RM3_MCROPT3';
    otherwise
        error('Unknown RM3 MCR option: %s', model);
end
label = char(model);
hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
    'RM3', 'hydroData');
cd(hydroDir);
if ~isfile('rm3.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Multiple_Condition_Runs', ...
    folder);
cd(caseDir);
wecSimMCR;
expectedHeader = {'waves.height', 'waves.period', ...
    'pto(1).damping', 'pto(1).stiffness'};
assert(isequal(mcr.header, expectedHeader), ...
    'Pinned RM3 MCR header changed');
assert(isequal(size(mcr.cases), [8, 4]), ...
    'Pinned RM3 MCR must contain eight four-parameter cases');
assert(numel(mcr.Avgpower) == 8 && all(isfinite(mcr.Avgpower)), ...
    'RM3 MCR did not calculate eight finite average powers');
assert(numel(mcr.CPTO) == 8 && all(isfinite(mcr.CPTO)), ...
    'RM3 MCR did not record eight finite PTO damping values');
writematrix([mcr.cases, mcr.Avgpower(:), mcr.CPTO(:)], ...
    fullfile(outDir, sprintf('%s_summary.csv', label)));

% Export the actual CData plotted by the pinned userDefinedFunctionsMCR.m.
% Its axes labels are transposed in the source example, but the tick values
% and 2-by-2 cell placement identify period rows and wave-height columns.
powerImages = findall(groot, 'Type', 'image');
foundD12 = false;
foundD24 = false;
for iImage = 1:numel(powerImages)
    matrix = double(powerImages(iImage).CData);
    if ~isequal(size(matrix), [2, 2])
        continue
    end
    axesHandle = ancestor(powerImages(iImage), 'axes');
    titleText = string(axesHandle.Title.String);
    if contains(titleText, 'Damping = 1200000')
        assert(~foundD12 && all(isfinite(matrix), 'all'), ...
            'RM3 MCR first power matrix is invalid');
        writematrix(matrix, fullfile(outDir, sprintf( ...
            '%s_power_matrix_D12.csv', label)));
        foundD12 = true;
    elseif contains(titleText, 'Damping = 2400000')
        assert(~foundD24 && all(isfinite(matrix), 'all'), ...
            'RM3 MCR second power matrix is invalid');
        writematrix(matrix, fullfile(outDir, sprintf( ...
            '%s_power_matrix_D24.csv', label)));
        foundD24 = true;
    end
end
assert(foundD12 && foundD24, ...
    'RM3 MCR did not plot both published PTO power matrices');

for iCase = 1:8
    saved = load(fullfile(caseDir, sprintf('savedData%03d.mat', iCase)), ...
        'output');
    assert(~isempty(saved.output.bodies) && isstruct(saved.output.ptos), ...
        'RM3 MCR savedData is missing motion or PTO output');
    for iBody = 1:numel(saved.output.bodies)
        response = saved.output.bodies(iBody);
        values = [response.time(:), response.position, response.velocity, ...
            response.forceTotal, response.forceExcitation];
        assert(all(isfinite(values), 'all'), ...
            'RM3 MCR body output contains nonfinite values');
        writematrix(values, fullfile(outDir, sprintf( ...
            '%s_case%d_body%d.csv', label, iCase, iBody)));
    end
    for iPto = 1:numel(saved.output.ptos)
        response = saved.output.ptos(iPto);
        values = [response.time(:), response.position, response.velocity, ...
            response.forceInternalMechanics, response.powerInternalMechanics];
        assert(all(isfinite(values), 'all'), ...
            'RM3 MCR PTO output contains nonfinite values');
        writematrix(values, fullfile(outDir, sprintf( ...
            '%s_case%d_pto%d.csv', label, iCase, iPto)));
    end
end
close_system('RM3', 0);
close all;
end

function run_rm3_mcr_seastate_baseline(repoRoot, outDir)
% Run the three published spectrumImport cases with their imported phases.
hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
    'RM3', 'hydroData');
cd(hydroDir);
if ~isfile('rm3.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Multiple_Condition_Runs', ...
    'RM3_MCROPT3_SeaState');
cd(caseDir);
wecSimMCR;
assert(isequal(mcr.header, {'waves.spectrumFile', 'simu.solver'}), ...
    'Pinned sea-state MCR header changed');
assert(isequal(size(mcr.cases), [3, 2]), ...
    'Pinned sea-state MCR must contain three cases');
assert(isequal(string(mcr.cases(:,1)), ...
    ["spectrumData1.mat"; "spectrumData2.mat"; "spectrumData3.mat"]), ...
    'Pinned sea-state MCR spectrum order changed');
assert(all(strcmp(mcr.cases(:,2), 'ode4')), ...
    'Pinned sea-state MCR solver changed');
assert(numel(mcr.Avgpower) == 3 && all(isfinite(mcr.Avgpower)), ...
    'Sea-state MCR did not calculate three finite powers');
writematrix(mcr.Avgpower(:), ...
    fullfile(outDir, 'RM3_MCR_SEASTATE_summary.csv'));
% Keep both mass matrices: MATLAB moves part of infinite-frequency added
% mass into the Simscape rigid body before each run, then restores the
% hydrodynamic matrix during postprocessing. The force output alone does
% not reveal which matrix the dynamics used.
for iBody = 1:numel(body)
    hydroForce = body(iBody).hydroForce.hf1;
    assert(isfield(hydroForce.storage, 'hydroForce_fAddedMass'), ...
        'Sea-state MCR is missing the applied added-mass matrix');
    writematrix(hydroForce.fAddedMass, fullfile(outDir, sprintf( ...
        'RM3_MCR_SEASTATE_body%d_added_mass_original.csv', iBody)));
    writematrix(hydroForce.storage.hydroForce_fAddedMass, ...
        fullfile(outDir, sprintf( ...
        'RM3_MCR_SEASTATE_body%d_added_mass_applied.csv', iBody)));
    properties = [body(iBody).mass, hydroForce.mass, ...
        hydroForce.adjustedMass, body(iBody).inertia, ...
        hydroForce.adjustedInertia];
    writematrix(properties, fullfile(outDir, sprintf( ...
        'RM3_MCR_SEASTATE_body%d_mass_properties.csv', iBody)));
end
for iCase = 1:3
    saved = load(fullfile(caseDir, sprintf('savedData%03d.mat', iCase)), ...
        'output', 'waves');
    assert(~isempty(saved.output.bodies) && isstruct(saved.output.ptos), ...
        'Sea-state MCR savedData is missing body or PTO output');
    components = [saved.waves.omega(:), saved.waves.amplitude(:), ...
        saved.waves.dOmega(:), saved.waves.phase(:)];
    assert(size(components, 2) == 4 && all(isfinite(components), 'all'), ...
        'Sea-state MCR has invalid wave components');
    writematrix(components, fullfile(outDir, sprintf( ...
        'RM3_MCR_SEASTATE_case%d_components.csv', iCase)));
    writematrix(saved.waves.waveAmpTime, fullfile(outDir, sprintf( ...
        'RM3_MCR_SEASTATE_case%d_wave.csv', iCase)));
    for iBody = 1:numel(saved.output.bodies)
        response = saved.output.bodies(iBody);
        values = [response.time(:), response.position, response.velocity, ...
            response.forceTotal, response.forceExcitation];
        assert(all(isfinite(values), 'all'), ...
            'Sea-state MCR body output contains nonfinite values');
        writematrix(values, fullfile(outDir, sprintf( ...
            'RM3_MCR_SEASTATE_case%d_body%d.csv', iCase, iBody)));
        forceValues = [response.time(:), response.forceRadiationDamping, ...
            response.forceAddedMass, response.forceRestoring, ...
            response.acceleration];
        assert(all(isfinite(forceValues), 'all'), ...
            'Sea-state MCR hydrodynamic forces contain nonfinite values');
        writematrix(forceValues, fullfile(outDir, sprintf( ...
            'RM3_MCR_SEASTATE_case%d_body%d_forces.csv', iCase, iBody)));
    end
    for iPto = 1:numel(saved.output.ptos)
        response = saved.output.ptos(iPto);
        values = [response.time(:), response.position, response.velocity, ...
            response.forceInternalMechanics, response.powerInternalMechanics];
        assert(all(isfinite(values), 'all'), ...
            'Sea-state MCR PTO output contains nonfinite values');
        writematrix(values, fullfile(outDir, sprintf( ...
            'RM3_MCR_SEASTATE_case%d_pto%d.csv', iCase, iPto)));
    end
end
close_system('RM3', 0);
close all;
end

function instrument_sphere_mpc()
% Add observation sinks to the disposable Actions checkout. The published
% controller blocks and connections are otherwise unchanged.
model = 'sphereMPC';
load_system([model '.slx']);
plant = [model '/Subsystem/Model Predictive Controller/Plant Model'];
optimizer = [model '/Subsystem/Model Predictive Controller/Optimizer'];
attach_mpc_trace(plant, 'Integrator', 1, ...
    'MPC paired full state', 'mpcFullState', 0);
attach_mpc_trace(optimizer, 'MATLAB Function1', 1, ...
    'MPC paired excitation prediction', 'mpcExcitationPrediction', 0);
attach_mpc_trace(optimizer, 'MATLAB Function', 1, ...
    'MPC paired command rate', 'mpcCommandRate', 0);
attach_mpc_trace(optimizer, 'MATLAB Function', 2, ...
    'MPC paired iteration', 'mpcIteration', 75);
save_system(model);
end

function attach_mpc_trace(parent, sourceName, outputNumber, sinkName, ...
    variableName, verticalOffset)
source = [parent '/' sourceName];
sourcePosition = get_param(source, 'Position');
sink = [parent '/' sinkName];
add_block('simulink/Sinks/To Workspace', sink, ...
    'VariableName', variableName, 'SaveFormat', 'Timeseries', ...
    'Position', [sourcePosition(3) + 90, ...
        sourcePosition(2) + verticalOffset, ...
        sourcePosition(3) + 180, ...
        sourcePosition(2) + verticalOffset + 30]);
sourcePorts = get_param(source, 'PortHandles');
sinkPorts = get_param(sink, 'PortHandles');
add_line(parent, sourcePorts.Outport(outputNumber), sinkPorts.Inport(1), ...
    'autorouting', 'on');
end

function export_mpc_trace(outDir, filename, trace, expectedWidth)
assert(isa(trace, 'timeseries'), 'MPC diagnostic trace is missing');
time = trace.Time(:);
values = squeeze(trace.Data);
if size(values, 1) ~= numel(time)
    values = values.';
end
assert(numel(time) > 1 && size(values, 1) == numel(time) && ...
    size(values, 2) == expectedWidth && ...
    all(isfinite(values), 'all'), ...
    'MPC diagnostic trace has invalid dimensions or values');
writematrix([time, values], fullfile(outDir, filename));
end
