% Pinned wecSim.m sequence with only MaxStep overridden after initialization.
run('initializeWecSim');
assert(abs(simu.dt - couplingStep) < 1e-12 && ...
    simu.dtOut == 0.01 && simu.endTime == 10 && ...
    strcmp(simu.solver, 'ode45') && waves.phaseSeed == 1 && ...
    mooring(1).moorDyn == 1, 'Audit settings changed');
[~, modelName, ~] = fileparts(simu.simMechanicsFile);
set_param(modelName, 'MaxStep', num2str(maximumStep, '%.15g'));
assert(abs(str2double(get_param(modelName, 'MaxStep')) - maximumStep) < 1e-12, ...
    'Could not set the independent ode45 maximum step');
sim(simu.simMechanicsFile, [], simset('SrcWorkspace', 'parent'));
run('stopWecSim');
