function rm3_moordyn_viz_baseline
% Run the pinned RM3 MoorDyn ParaView settings with a fixed sea realization.
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
outDir = fullfile(repoRoot, 'matlab-rm3-moordyn-viz');
if ~isfolder(outDir)
    mkdir(outDir);
end
hydroDir = fullfile(repoRoot, 'applications', '_Common_Input_Files', ...
    'RM3', 'hydroData');
cd(hydroDir);
if ~isfile('rm3.h5')
    bemio;
end
caseDir = fullfile(repoRoot, 'applications', 'Paraview_Visualization', ...
    'RM3_MoorDyn_Viz');
% The published input leaves the random phase seed open. Choose the same
% seed as the focused step-refinement run so the full case is reproducible.
seededDir = fullfile(fileparts(caseDir), 'RM3_MoorDyn_Viz_seed1_80s');
mkdir(seededDir);
for name = {'wecSimInputFile.m', 'RM3MoorDyn.slx', ...
        'userDefinedFunctions.m'}
    copyfile(fullfile(caseDir, name{1}), fullfile(seededDir, name{1}));
end
mkdir(fullfile(seededDir, 'Mooring'));
copyfile(fullfile(caseDir, 'Mooring', 'lines.txt'), ...
    fullfile(seededDir, 'Mooring', 'lines.txt'));
inputFile = fullfile(seededDir, 'wecSimInputFile.m');
contents = fileread(inputFile);
assert(contains(contents, 'waves.period = 8;') && ...
    ~contains(contents, 'waves.phaseSeed'), ...
    'The pinned RM3 MoorDyn visualization input changed');
contents = strrep(contents, 'waves.period = 8;', ...
    sprintf('waves.period = 8;\nwaves.phaseSeed = 1;'));
fid = fopen(inputFile, 'w');
assert(fid > 0);
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, contents);
clear cleanup;
cd(seededDir);
wecSim;

assert(simu.dt == 0.01 && simu.dtOut == 0.1 && simu.cicDt == 0.05 && ...
    simu.endTime == 80 && simu.rampTime == 0 && ...
    strcmp(simu.solver, 'ode45') && simu.paraview.option == 1 && ...
    strcmp(waves.type, 'irregular') && ...
    strcmp(waves.spectrumType, 'JS') && ...
    strcmp(waves.bem.option, 'Traditional') && ...
    waves.height == 2 && waves.period == 8 && waves.phaseSeed == 1 && ...
    waves.waterDepth == 70 && ...
    numel(waves.omega) == 1000 && ...
    numel(output.bodies) == 2 && numel(output.ptos) == 1 && ...
    mooring(1).moorDyn == 1 && mooring(1).moorDynLines == 3 && ...
    isequal(mooring(1).moorDynNodes, [21 21 21]), ...
    'The pinned RM3 MoorDyn visualization input changed');
components = [waves.omega(:), waves.dOmega(:), ...
    waves.spectrum(:), waves.phase(:)];
assert(size(components, 1) == 1000 && ...
    all(isfinite(components), 'all'), ...
    'The source sea components are incomplete');
writematrix(components, fullfile(outDir, 'components.csv'));
writematrix(waves.phase(:), fullfile(outDir, 'phase.csv'));
writematrix([output.wave.time(:), output.wave.elevation(:)], ...
    fullfile(outDir, 'wave.csv'));
for iBody = 1:2
    record = output.bodies(iBody);
    values = [record.time(:), record.position, record.velocity, ...
        record.forceTotal, record.forceExcitation];
    assert(size(values, 2) == 25 && all(isfinite(values), 'all'), ...
        'The source body record is incomplete');
    writematrix(values, fullfile(outDir, sprintf('body%d.csv', iBody)));
end
record = output.ptos(1);
values = [record.time(:), record.position, record.velocity, ...
    record.forceInternalMechanics, record.powerInternalMechanics];
assert(size(values, 2) == 25 && all(isfinite(values), 'all'), ...
    'The source PTO record is incomplete');
writematrix(values, fullfile(outDir, 'pto.csv'));
record = output.mooring(1);
values = [record.time(:), record.position, record.velocity, ...
    record.forceMooring];
assert(size(values, 2) == 19 && all(isfinite(values), 'all'), ...
    'The source mooring record is incomplete');
writematrix(values, fullfile(outDir, 'mooring.csv'));
assert(isstruct(output.moorDyn) && ...
    isfield(output.moorDyn(1), 'Lines') && ...
    all(isfield(output.moorDyn(1).Lines, ...
    {'Time', 'FairTen1', 'FairTen2', 'FairTen3'})), ...
    'The source fairlead tension output is missing');
lines = output.moorDyn(1).Lines;
writematrix([lines.Time(:), lines.FairTen1(:), ...
    lines.FairTen2(:), lines.FairTen3(:)], ...
    fullfile(outDir, 'fairlead_tension.csv'));
close_system('RM3MoorDyn', 0);
end
