% Pinned wecSim.m sequence, changing only ode45 MaxStep after setup.
run('initializeWecSim');
assert(simu.dt == 0.01 && simu.dtOut == 0.01 && ...
    simu.endTime == 80 && simu.rampTime == 0 && ...
    strcmp(simu.solver, 'ode45') && waves.phaseSeed == 1 && ...
    mooring(1).moorDyn == 1, 'Full solver-step settings changed');
[~, modelName, ~] = fileparts(simu.simMechanicsFile);
set_param(modelName, 'MaxStep', '0.0003125');
assert(abs(str2double(get_param(modelName, 'MaxStep')) ...
    - 0.0003125) < 1e-12, 'Could not set ode45 MaxStep');
sim(simu.simMechanicsFile, [], simset('SrcWorkspace', 'parent'));
run('stopWecSim');
