function rm3_moordyn_viz_dense_diagnostic
% Save every MoorDyn coupling step from a short derived source run.
repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repoRoot, 'matlab-ref', 'source')));
caseDir = fullfile(repoRoot, 'applications', 'Paraview_Visualization', ...
    'RM3_MoorDyn_Viz');
denseDir = fullfile(fileparts(caseDir), 'RM3_MoorDyn_Viz_dense');
copyCaseInputs(caseDir, denseDir);
inputFile = fullfile(denseDir, 'wecSimInputFile.m');
contents = fileread(inputFile);
changes = {
    'simu.endTime = 80;', 'simu.endTime = 10;';
    'simu.dtOut = 0.1;', 'simu.dtOut = 0.01;';
    'simu.paraview.option = 1;', 'simu.paraview.option = 0;';
    'waves.period = 8;', sprintf('waves.period = 8;\nwaves.phaseSeed = 1;')
};
for i = 1:size(changes, 1)
    assert(contains(contents, changes{i, 1}), ...
        'The pinned RM3 MoorDyn visualization input changed');
    contents = strrep(contents, changes{i, 1}, changes{i, 2});
end
fid = fopen(inputFile, 'w');
assert(fid > 0);
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, contents);
clear cleanup;
cd(denseDir);
wecSim;
assert(simu.dt == 0.01 && simu.dtOut == 0.01 && ...
    simu.endTime == 10 && strcmp(simu.solver, 'ode45') && ...
    waves.phaseSeed == 1 && mooring(1).moorDyn == 1, ...
    'The dense coupling diagnostic settings changed');
record = output.mooring(1);
values = [record.time(:), record.position, record.velocity, ...
    record.forceMooring];
assert(size(values, 1) == 1001 && size(values, 2) == 19 && ...
    all(isfinite(values), 'all'), ...
    'The dense source mooring record is incomplete');
outDir = fullfile(repoRoot, 'matlab-rm3-moordyn-viz');
writematrix(values, fullfile(outDir, 'dense_mooring.csv'));
writematrix(waves.phase(:), fullfile(outDir, 'dense_phase.csv'));
writematrix([output.wave.time(:), output.wave.elevation(:)], ...
    fullfile(outDir, 'dense_wave.csv'));
for iBody = 1:2
    bodyRecord = output.bodies(iBody);
    bodyValues = [bodyRecord.time(:), bodyRecord.position, ...
        bodyRecord.velocity, bodyRecord.forceTotal, ...
        bodyRecord.forceExcitation];
    assert(size(bodyValues, 1) == 1001 && ...
        size(bodyValues, 2) == 25 && all(isfinite(bodyValues), 'all'), ...
        'The dense source body record is incomplete');
    writematrix(bodyValues, fullfile(outDir, ...
        sprintf('dense_body%d.csv', iBody)));
    forceValues = [bodyRecord.time(:), bodyRecord.acceleration, ...
        bodyRecord.forceExcitation, bodyRecord.forceRadiationDamping, ...
        bodyRecord.forceAddedMass, bodyRecord.forceRestoring, ...
        bodyRecord.forceMorisonAndViscous, bodyRecord.forceLinearDamping, ...
        bodyRecord.forceTotal];
    assert(size(forceValues, 1) == 1001 && ...
        size(forceValues, 2) == 49 && all(isfinite(forceValues), 'all'), ...
        'The dense source force components are incomplete');
    writematrix(forceValues, fullfile(outDir, ...
        sprintf('dense_forces_body%d.csv', iBody)));
end
close_system('RM3MoorDyn', 0);

% Keep the same short seeded sea and physical settings, but restore the
% published 0.1 s output interval to test source output-step sensitivity.
coarseDir = fullfile(fileparts(caseDir), 'RM3_MoorDyn_Viz_coarse');
copyCaseInputs(caseDir, coarseDir);
coarseFile = fullfile(coarseDir, 'wecSimInputFile.m');
coarseInput = fileread(coarseFile);
coarseChanges = {
    'simu.endTime = 80;', 'simu.endTime = 10;';
    'simu.paraview.option = 1;', 'simu.paraview.option = 0;';
    'waves.period = 8;', sprintf('waves.period = 8;\nwaves.phaseSeed = 1;')
};
for i = 1:size(coarseChanges, 1)
    assert(contains(coarseInput, coarseChanges{i, 1}), ...
        'The pinned RM3 MoorDyn visualization input changed');
    coarseInput = strrep(coarseInput, coarseChanges{i, 1}, ...
        coarseChanges{i, 2});
end

fid = fopen(coarseFile, 'w');
assert(fid > 0);
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, coarseInput);
clear cleanup;
cd(coarseDir);
wecSim;
assert(simu.dt == 0.01 && simu.dtOut == 0.1 && ...
    simu.endTime == 10 && strcmp(simu.solver, 'ode45') && ...
    waves.phaseSeed == 1 && mooring(1).moorDyn == 1, ...
    'The coarse coupling diagnostic settings changed');
writematrix(waves.phase(:), fullfile(outDir, 'coarse_phase.csv'));
writematrix([output.wave.time(:), output.wave.elevation(:)], ...
    fullfile(outDir, 'coarse_wave.csv'));
record = output.mooring(1);
values = [record.time(:), record.position, record.velocity, ...
    record.forceMooring];
assert(size(values, 1) == 101 && size(values, 2) == 19 && ...
    all(isfinite(values), 'all'), ...
    'The coarse source mooring record is incomplete');
writematrix(values, fullfile(outDir, 'coarse_mooring.csv'));
for iBody = 1:2
    bodyRecord = output.bodies(iBody);
    bodyValues = [bodyRecord.time(:), bodyRecord.position, ...
        bodyRecord.velocity, bodyRecord.forceTotal, ...
        bodyRecord.forceExcitation];
    assert(size(bodyValues, 1) == 101 && ...
        size(bodyValues, 2) == 25 && all(isfinite(bodyValues), 'all'), ...
        'The coarse source body record is incomplete');
    writematrix(bodyValues, fullfile(outDir, ...
        sprintf('coarse_body%d.csv', iBody)));
end
close_system('RM3MoorDyn', 0);

% Repeat the dense diagnostic with an independent phase realization. This
% tests whether the startup-feedback attribution is specific to seed 1.
seed2Dir = fullfile(fileparts(caseDir), 'RM3_MoorDyn_Viz_seed2');
copyCaseInputs(caseDir, seed2Dir);
seed2File = fullfile(seed2Dir, 'wecSimInputFile.m');
seed2Input = fileread(seed2File);
seed2Changes = {
    'simu.endTime = 80;', 'simu.endTime = 10;';
    'simu.dtOut = 0.1;', 'simu.dtOut = 0.01;';
    'simu.paraview.option = 1;', 'simu.paraview.option = 0;';
    'waves.period = 8;', sprintf('waves.period = 8;\nwaves.phaseSeed = 2;')
};
for i = 1:size(seed2Changes, 1)
    assert(contains(seed2Input, seed2Changes{i, 1}), ...
        'The pinned RM3 MoorDyn visualization input changed');
    seed2Input = strrep(seed2Input, seed2Changes{i, 1}, ...
        seed2Changes{i, 2});
end
fid = fopen(seed2File, 'w');
assert(fid > 0);
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, seed2Input);
clear cleanup;
cd(seed2Dir);
wecSim;
assert(simu.dt == 0.01 && simu.dtOut == 0.01 && ...
    simu.endTime == 10 && strcmp(simu.solver, 'ode45') && ...
    waves.phaseSeed == 2 && mooring(1).moorDyn == 1, ...
    'The second dense coupling settings changed');
record = output.mooring(1);
values = [record.time(:), record.position, record.velocity, ...
    record.forceMooring];
assert(size(values, 1) == 1001 && size(values, 2) == 19 && ...
    all(isfinite(values), 'all'), ...
    'The second dense source mooring record is incomplete');
writematrix(values, fullfile(outDir, 'seed2_dense_mooring.csv'));
writematrix(waves.phase(:), fullfile(outDir, 'seed2_dense_phase.csv'));
writematrix([output.wave.time(:), output.wave.elevation(:)], ...
    fullfile(outDir, 'seed2_dense_wave.csv'));
for iBody = 1:2
    bodyRecord = output.bodies(iBody);
    bodyValues = [bodyRecord.time(:), bodyRecord.position, ...
        bodyRecord.velocity, bodyRecord.forceTotal, ...
        bodyRecord.forceExcitation];
    forceValues = [bodyRecord.time(:), bodyRecord.acceleration, ...
        bodyRecord.forceExcitation, bodyRecord.forceRadiationDamping, ...
        bodyRecord.forceAddedMass, bodyRecord.forceRestoring, ...
        bodyRecord.forceMorisonAndViscous, bodyRecord.forceLinearDamping, ...
        bodyRecord.forceTotal];
    assert(size(bodyValues, 1) == 1001 && size(bodyValues, 2) == 25 && ...
        size(forceValues, 1) == 1001 && size(forceValues, 2) == 49 && ...
        all(isfinite(bodyValues), 'all') && ...
        all(isfinite(forceValues), 'all'), ...
        'The second dense source body record is incomplete');
    writematrix(bodyValues, fullfile(outDir, ...
        sprintf('seed2_dense_body%d.csv', iBody)));
    writematrix(forceValues, fullfile(outDir, ...
        sprintf('seed2_dense_forces_body%d.csv', iBody)));
end
end

function copyCaseInputs(caseDir, targetDir)
mkdir(targetDir);
for name = {'wecSimInputFile.m', 'RM3MoorDyn.slx', ...
        'userDefinedFunctions.m'}
    copyfile(fullfile(caseDir, name{1}), fullfile(targetDir, name{1}));
end
mkdir(fullfile(targetDir, 'Mooring'));
copyfile(fullfile(caseDir, 'Mooring', 'lines.txt'), ...
    fullfile(targetDir, 'Mooring', 'lines.txt'));
end
